### ISSUE TITLE
sops now tries to encrypt any file that has a .yaml extension

### ISSUE THREAD

**Issue by Gui13** [signageos/vscode-sops#10]
Version 0.1.0 broke this feature.

I used to use sops only on my gitops repos, and the extension is enabled globally.

Now, when I modify any yaml file in unrelated projects, sops tries to encrypt the file.

Could you maybe try to see if there is a .sops.yaml at the root of the project before hijcking the save of any .yaml file?

**Comment by Morriz** [comment]
Yeah, it is way too greedy. I think you should add a pattern matcher to your settings. I would set the default to the `helm secrets` one: `secrets.*.yaml`

**Comment by misak113** [comment]
Hi, sorry for the incompatibility in the new minor version 0.1.0.
The auto encryption of new matched files in .sops.yaml is now temporarily conditioned by global config `sops.creationEnabled` which is disabled by default in hotfix version **0.1.1**.
See https://marketplace.visualstudio.com/items?itemName=signageos.signageos-vscode-sops
Related to https://github.com/signageos/vscode-sops/commit/4baff27f961e8c1e3fc92104d07434ca07132e49
