### ISSUE TITLE
gcpCredentialsPath not working with relative path from root

### ISSUE THREAD

**Issue by Morriz** [signageos/vscode-sops#11]
Hard path is working, but that defeats the purpose.

I've tried both ways to get this to work

`${workspaceFolder}/gcp-key.json`
`./gcp-key.json`

But decryption always fails :|

I would expect this plugin to have its $PWD set to the root dir of the vscode project: ${workspaceFolder}.

**Comment by misak113** [comment]
Ok, I forgot the relative path resolving. Updated.. upgrade to version 0.1.2 pls.
Here is the fix https://github.com/signageos/vscode-sops/commit/6c3eb7c2ac0528df53f7c0d83e80f304defb8c97

**Comment by Morriz** [comment]
awesome!
