### ISSUE TITLE
Error: UNKNOWN: unknown error, open '\\e:\path\.decrypted~secrets.yaml')

### ISSUE THREAD

**Issue by tstmrk** [signageos/vscode-sops#13]
On Windows I am getting the following error.

`Could not decrypt SOPS file e:\path\secrets.yaml: Unable to write file '\\e:\path\.decrypted~secrets.yaml' (Unknown (FileSystemError): Error: UNKNOWN: unknown error, open '\\e:\path\.decrypted~secrets.yaml')
`

Why is it trying to write a file with path starting with "\\e:"?

**Comment by misak113** [comment]
Hi, thank you for the issue. Sadly, the extension is officially currently supported only on *nix systems. I have no Windows environment to test it on. Any pull requests are welcome.

However, the Remote Development over SSH in WSL or remote Linux server should work.

**Comment by tstmrk** [comment]
Aahh, that's too bad. Thanks for your quick reply. But I managed to get it in combination with the Remote WSL plugin.
