### ISSUE TITLE
allow disabling of automatic handling of files

### ISSUE THREAD

**Issue by Morriz** [signageos/vscode-sops#15]
It is sometimes handy to see the encrypted file. I see the following additions:

- an icon in the bottom bar to disable/re-enable the "automatic" function
- context menu items "Show encrypted contents" and "Show decrypted contents"

**Comment by misak113** [comment]
I introduced the beta releases: https://github.com/signageos/vscode-sops#beta-releases
The new beta version with this feature is available at v0.3.0-beta.1 https://marketplace.visualstudio.com/items?itemName=signageos.signageos-vscode-sops-beta

**Comment by Morriz** [comment]
Awesome!
