### ISSUE TITLE
extension does not work when only enabled in workspace

### ISSUE THREAD

**Issue by Morriz** [signageos/vscode-sops#21]
Hi again, I have disabled the extension globally to only enable it in certain repos. That does not work however. Only turning it on globally seems to work, but then it constantly complains about not being able to work with arbitrary yaml files that don't even have a sops property in them (I will create a separate issue for that). Other extensions don't suffer from the fine grained enablement approach. It seems to do with your extension.

**Comment by Morriz** [comment]
Ok, I see now the issue is in your interface not propagating the "sops.enabled": true part to the `.vscode/settings.json` when toggling the checkbox in the user context.

If I add that line to the settings file manually it starts to work. After that I can disable it from the ui and it is reflected in the file.

However, if I then ENABLE it again, the whole line is removed from that file, effectively disabling the user change and falling back to global, which has enabled=false

**Comment by misak113** [comment]
I'm not sure where the problem finally is. I use the default behavior of vscode API, which returns me the closest configuration of current scope:
`vscode.workspace.getConfiguration(CONFIG_BASE_SECTION).get(ConfigName.enabled)`

To my knowledge, the behavior is looking for the workspace config (if you are in workspace env). Then look for local .vscode/settings.json file configs if available. If not, it looks to your user global settings.json. And if even this is not available, set the extension defaults.

**Comment by Morriz** [comment]
The problem is that every time the workspace settings get changed, the option "sops.enabled" is erased when it is set to true. Workspace settings should NEVER be removed by a plugin.

**Comment by Morriz** [comment]
I am assuming that it is the plugin removing that setting, because I have not seen this problem before with other plugins. But I will quickly check.
