### ISSUE TITLE
extension complains about not being able to operate on arbitrary yaml files

### ISSUE THREAD

**Issue by Morriz** [signageos/vscode-sops#22]
Hi, turning on your extension makes it complain about yaml files that should not be of its concern.

I would expect the extension to remain idle without a `.sops.yaml` file in the repo.

**Comment by misak113** [comment]
Hi,
it looks that it's not that simple.
There is a use case where .sops.yaml is not present in the project.
As long as .sops.yaml configuration is optional, I have to figure it out a different way.

The MR will come soon.

**Comment by misak113** [comment]
Fix is available in beta 0.4.0-beta.1 https://marketplace.visualstudio.com/items?itemName=signageos.signageos-vscode-sops-beta 
See https://github.com/signageos/vscode-sops#beta-releases

MR: https://github.com/signageos/vscode-sops/pull/24
