### ISSUE TITLE
Does not work with text files

### ISSUE THREAD

**Issue by jojoxd** [signageos/vscode-sops#47]
Sops can encrypt text files ([any file as binary](https://github.com/mozilla/sops#encrypting-binary-files)) into a json file that can be decrypted back to text:

```
=> sops --encrypt my-file.txt --input-type text
<= {
        "data": "<snip>",
        "sops": {
                <snip>
        }
}
```

```
=> sops --decrypt my-file.txt.enc --input-type json --output-type text
<= my file content
```

However, this extension does not support this. I want to use this for encrypting an Ansible private/public key pair that will live in a public git repository.

This would somewhat be possible to implement with `path_regex` in the `.sops.yaml` configuration file. The only thing is that this would assume the content of the file using its extension, which should, of course, never be assumed.

**Comment by misak113** [comment]
Ok, released under beta version
https://marketplace.visualstudio.com/items?itemName=signageos.signageos-vscode-sops-beta

See enabling beta releases in README.md file

**Comment by jojoxd** [comment]
works like a charm!
