### ISSUE TITLE
Does not work with arbitrary file extension

### ISSUE THREAD

**Issue by introom** [signageos/vscode-sops#49]
For example, I have an sops-encrypted file `my.py.enc`.  

The vanilla file extension is `py`.

With `sops`, the file content is put inside the `data` field of the json file `my.py.enc`.

vscode-sops works fine when the decrypted file is of `plaintext` format, however, when I set the following in vsocde:
```
  "files.associations": {
    "*.json": "jsonc",
    ".decrypted*.py.enc": "python",
  },
```
Then, when I save the `.decrypte~my.py.enc` file, encryption no longer works.

**Comment by misak113** [comment]
Ok, released under beta version
https://marketplace.visualstudio.com/items?itemName=signageos.signageos-vscode-sops-beta

See enabling beta releases in README.md file

**Comment by introom** [comment]
Awesome!
