### ISSUE TITLE
error decrypting a file: "spawnSync sops ENOENT" (2022)

### ISSUE THREAD

**Issue by dzivkovic6** [signageos/vscode-sops#50]
Hi! I'm having a trouble using a SOPS extension, I did follow the similar topic but without success with fixing it.

Error is:

Could not decrypt SOPS file <path of the file...> spawnSync sops ENOENT

macOS Montrey 12.3.1 m1
VS Code 1.69
node v14, 16

**Comment by misak113** [comment]
https://github.com/signageos/vscode-sops/issues/4

**Comment by misak113** [comment]
Duplicated.
