### ISSUE TITLE
How to configure vscode-sops with 'age'

### ISSUE THREAD

**Issue by eugeis** [signageos/vscode-sops#51]
Hello,

I am using sops with [age](https://github.com/mozilla/sops#encrypting-using-age). 

How to configure vscode-sops for editing? I tried it with '.sops.yaml' in the workspace 

creation_rules:
  - '.path_regex: '.*\.sops\.(yaml|ini|json|env|key|text)$'
    age: .....

and set SOPS_AGE_KEY_FILE and SOPS_AGE_KEY environment variables, but when I open an encrypted xy.sops.yaml file in VSCode, it stays encrypted.

Please advice, thanks

**Comment by eugeis** [comment]
Thanks you very much.

The usage of SOPS with AGE is easy:

System setup
- Install [AGE](https://github.com/FiloSottile/age) and put it to PATH
- Generate AGE public and private key
`age-keygen -o age.txt`
- Set environment variables SOPS_AGE_KEY_FILE=age.txt (path of generated age key file, which age private key) and SOPS_AGE_KEY=<public keys / age recipients>

SOPS detects automatically, that AGE shall be used if those variables are set, so SOPS --encrypt / --decrypt / edit can be used with out additional parameters but only the file path.

There is also possible to work without those environment variables, then --age/-a parameter shall be used by SOPS.

**Comment by misak113** [comment]
Ok, released under beta version
https://marketplace.visualstudio.com/items?itemName=signageos.signageos-vscode-sops-beta

See enabling beta releases in README.md file

**Comment by eugeis** [comment]
Great, I will check it out.

**Comment by eugeis** [comment]
Thank you, it works fine.
