### ISSUE TITLE
allow setting for env var GOOGLE_APPLICATION_CREDENTIALS

### ISSUE THREAD

**Issue by Morriz** [signageos/vscode-sops#6]
It is cumbersome to have to restart vscode with new env that points to another account file. We work with multiple customers and thus accounts.

So would you please create a setting to override the GOOGLE_APPLICATION_CREDENTIALS env var?

**Comment by Morriz** [comment]
Would be nice to configure any Sops related credential pointing env vars in a repo file that points where to find creds.
So for aws it could point to a profile, and for google it could point to a relative file path to the aformentioned var.
Without such pointers it's a drag to use multiple kms providers or kms accounts

**Comment by misak113** [comment]
Hi Morriz,
I'd like to know more of how would you imagine the options in vscode extension? I can provide my draft. Requesting you for a feedback?
Currently, I'm familiar just with AWS KMS service. Not the google KMS provider.

For AWS KMS it could looks like this:
https://github.com/signageos/vscode-sops/pull/7

**Comment by misak113** [comment]
Published. It's ready to go: https://marketplace.visualstudio.com/items?itemName=signageos.signageos-vscode-sops
